influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
  
telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
        - influxdb

grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
        - "3000:3000"
    user: "0"
    links:
        - influxdb
